services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7.0.5-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
